disabled_rules:
  - force_try
  - line_length
  - trailing_whitespace
  - force_cast
  - colon
  - variable_name
  - conditional_binding_cascade
  - function_body_length
included:
  - Broad
excluded:
  - Broad/Resources/R.generated.swift
