osx_image: xcode10.1
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8
    - COMMIT_TEXT="$(git log --no-merges --format=%B $TRAVIS_COMMIT_RANGE)"
    - DISTRIBUTION_NOTES_FILE=distribution_notes.txt
    - COMMIT_SHA1=$TRAVIS_COMMIT
    - BUILD_URL="https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
    - REPOSITORY_URL="https://github.com/$TRAVIS_REPO_SLUG"
    - CONFIGURATION=AdHoc

cache:
  bundler: true
  directories:
    - Carthage

install:
  - brew update && brew bundle
  - bundle install
  - carthage bootstrap --platform ios --cache-builds

before_script:
  - xcrun agvtool new-version -all "$TRAVIS_BUILD_NUMBER"

script:
  - bundle exec fastlane test

after_success:
  - |
      # setup ssh_key for fastlane match
      declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
      openssl aes-256-cbc \
        -K $encrypted_31ae002cee1e_key \
        -iv $encrypted_31ae002cee1e_iv \
        -in ".travis/github_deploy_key.enc" \
        -out "$SSH_FILE" -d
      chmod 600 "$SSH_FILE" \
        && printf "%s\n" \
             "Host github.com" \
             "  StrictHostKeyChecking no" \
             "  IdentityFile $SSH_FILE" \
             "  LogLevel ERROR" >> ~/.ssh/config
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      bundle exec fastlane ci_beta
    fi

notifications:
  slack: delanoir:VvO4iLPEMOWzmcd9a6HRO3am
