default_platform(:ios)

platform :ios do
  desc "Run Tests"
  lane :test do
    run_tests(scheme: "Broad")
  end

  lane :build do |options|
    build_app(
      scheme: "Broad",
      configuration: options[:config] || "Release",
      export_method: options[:export] || "development"
    )
  end

  lane :beta do
    sync_code_signing(
      type: "adhoc"
    )
    build(
      config: "AdHoc",
      export: "ad-hoc"
    )
    hockey
  end

  lane :store do
    sync_code_signing(
      type: "appstore",
      keychain_password: ENV['KEYCHAIN_PASSWORD']
    )
    build(
      config: "AppStore",
      export: "app-store"
    )
  end

  desc "Build and Release on HockeyApp"
  lane :ci_beta do
    keychain_name = "ios-build.keychain"
    create_keychain(
      name: keychain_name,
      password: ENV['KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    sync_code_signing(
      git_url: 'https://github.com/carlossless/apple-certificates.git',
      keychain_name: keychain_name,
      keychain_password: ENV['KEYCHAIN_PASSWORD'],
      type: "adhoc",
      readonly: true
    )
    build(
      config: "AdHoc",
      export: "ad-hoc"
    )
    appcenter_upload(
      owner_name: 'delanoir-omy0',
      owner_type: 'organization',
      app_name: 'Broad',
      notify_testers: true
    )
  end
end
