default_platform(:ios)

platform :ios do
  desc "Run Tests"
  lane :test do
    run_tests(scheme: "Broad")
  end

  lane :build do |options|
    sync_code_signing(
      readonly: true
    )
    build_app(
      scheme: "Broad",
      configuration: options[:config] || "Release",
      export_method: options[:export] || "development"
    )
  end

  lane :beta do
    sync_code_signing(
      type: "adhoc"
    )
    build(
      config: "AdHoc",
      export: "ad-hoc"
    )
    hockey
  end

  lane :appstore do
    sync_code_signing(
      type: "appstore",
        keychain_password: "operator12"
    )
    build(
      config: "AppStore",
      export: "app-store"
    )
  end

  desc "Build and Release on HockeyApp"
  lane :ci_beta do
    keychain_name = "ios-build.keychain"
    create_keychain(
      name: keychain_name,
      password: ENV['KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    sync_code_signing(
      keychain_name: keychain_name,
      keychain_password: ENV['KEYCHAIN_PASSWORD'],
      type: "adhoc",
      readonly: true
    )
    increment_build_number(
      build_number: ENV['TRAVIS_BUILD_NUMBER']
    )
    build(
      config: "AdHoc",
      export: "ad-hoc"
    )
    hockey
  end
end
