name: beta

on: 
  push:
    branches:
      - master

jobs:
  release:
    name: Beta Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove Existing swiftlint
        run: rm /usr/local/bin/swiftlint
      - name: Homebrew Bundle
        run: brew bundle
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
      - name: Ruby Bundle
        run: bundle install --path vendor/bundle
      - uses: actions/cache@v1
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      - name: Carthage
        if: steps.carthage-cache.outputs.cache-hit != 'true'
        run: carthage bootstrap --platform iOS --cache-builds
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set build number
        run: xcrun agvtool new-version -all "$GITHUB_RUN_ID"
      - name: Beta Release
        run: bundle exec fastlane ci_beta
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
